In [1]:
import numpy as np
from data import WIDERFACE

In [2]:
wf = WIDERFACE('/Users/fengyuantao/playground/datasets/widerface', '/Users/fengyuantao/playground/datasets/widerface/eval_tools')


In [3]:
valset_easy = wf.valset_easy_filepaths

In [4]:
valset = []
with open('/Users/fengyuantao/playground/datasets/widerface/wider_face_split/wider_face_val_bbx_gt.txt', 'r') as valf:
    for line in valf:
        if '.jpg' in line:
            valset.append(line.strip())

In [5]:
print(len(valset))
print(valset[0])
print(valset_easy[0])

3226
0--Parade/0_Parade_marchingband_1_465.jpg
0--Parade/0_Parade_marchingband_1_465.jpg


In [6]:
for i in valset_easy:
    flag = False
    for j in valset:
        if i == j:
            flag = True
    if not flag:
        print('unmatched')
        break

In [19]:
# next check whether the gt_list will be empty
import scipy.io as sio

easy_mat = sio.loadmat('/Users/fengyuantao/playground/datasets/widerface/eval_tools/ground_truth/wider_easy_val.mat')
print(easy_mat.keys())

for event_id in range(len(easy_mat['event_list'])):
    for img_id in range(len(easy_mat['file_list'][event_id][0])):
        print(easy_mat['gt_list'][event_id][0][img_id][0])

dict_keys(['__header__', '__version__', '__globals__', 'blur_label_list', 'event_list', 'expression_label_list', 'face_bbx_list', 'file_list', 'gt_list', 'illumination_label_list', 'invalid_label_list', 'occlusion_label_list', 'pose_label_list'])
[]
[]
[]
[[1]
 [2]
 [3]
 [4]
 [5]]
[]
[]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]]
[]
[[8]]
[[1]]
[]
[[1]
 [2]]
[]
[[1]
 [2]]
[]
[]
[]
[[ 1]
 [19]]
[[ 1]
 [ 2]
 [19]]
[]
[[1]
 [2]
 [3]
 [4]]
[]
[[1]
 [2]
 [3]]
[[1]
 [3]
 [4]
 [6]]
[[1]
 [2]]
[]
[]
[[12]]
[]
[]
[]
[[1]
 [2]
 [3]]
[]
[]
[[1]
 [2]]
[[ 4]
 [12]]
[[6]
 [7]]
[]
[]
[[13]]
[[20]]
[[1]]
[[1]]
[[4]]
[[1]
 [2]
 [3]
 [4]
 [5]]
[[ 2]
 [ 6]
 [ 7]
 [10]]
[[1]
 [2]
 [3]
 [4]]
[]
[]
[[ 1]
 [23]
 [24]
 [25]
 [35]]
[]
[]
[[4]
 [5]]
[[10]]
[]
[]
[[1]
 [2]
 [3]
 [4]
 [5]]
[]
[[  9]
 [ 20]
 [ 22]
 [ 23]
 [ 24]
 [ 25]
 [ 26]
 [ 55]
 [ 56]
 [ 59]
 [ 62]
 [ 63]
 [ 64]
 [ 96]
 [ 97]
 [ 98]
 [100]
 [101]]
[[1]
 [2]
 [3]

 [13]]
[[ 2]
 [ 3]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [12]]
[]
[[1]
 [3]
 [4]
 [5]
 [6]]
[[1]
 [2]]
[[ 1]
 [ 2]
 [ 3]
 [ 5]
 [13]
 [18]]
[[1]]
[[3]
 [9]]
[[1]
 [2]
 [3]
 [4]]
[[1]
 [2]
 [3]
 [4]]
[[1]
 [2]]
[[1]]
[]
[]
[[1]
 [2]]
[[1]
 [2]
 [3]
 [5]
 [6]]
[]
[[4]]
[[1]
 [2]
 [3]
 [4]
 [5]]
[[ 3]
 [10]]
[[12]
 [13]]
[[ 1]
 [13]
 [14]
 [27]
 [30]
 [31]
 [33]
 [35]]
[[ 8]
 [16]]
[[65]]
[[1]
 [2]
 [3]
 [5]
 [9]]
[]
[]
[[ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [11]
 [15]
 [16]
 [17]]
[]
[[2]]
[[1]
 [2]
 [3]
 [4]]
[]
[]
[[ 5]
 [ 6]
 [ 7]
 [12]
 [18]
 [25]
 [80]]
[]
[[31]]
[]
[[ 3]
 [ 5]
 [ 6]
 [ 8]
 [10]
 [12]
 [13]
 [19]]
[[1]
 [2]
 [4]]
[[3]
 [5]
 [8]
 [9]]
[[2]
 [3]
 [4]]
[[1]
 [2]
 [3]]
[[ 6]
 [ 8]
 [ 9]
 [10]
 [11]]
[[1]
 [2]]
[[1]
 [2]]
[[1]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[1]
 [4]
 [5]
 [7]]
[[1]
 [2]
 [3]
 [4]
 [5]]
[[1]
 [4]
 [5]
 [6]]
[[1]
 [4]
 [5]]
[[ 1]
 [ 2]
 [ 5]
 [ 6]
 [10]
 [16]
 [17]]
[[26]
 [32]
 [34]
 [35]
 [36]]
[[ 1]
 [ 2]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [11]]
[[1]
 [

[[1]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
[[1]
 [3]
 [4]
 [6]]
[[1]]
[[1]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [9]]
[[1]]
[[1]]
[[1]
 [2]]
[[1]
 [2]]
[[1]]
[]
[[1]]
[]
[[1]
 [2]]
[[1]
 [2]
 [3]]
[[1]]
[[1]
 [2]]
[]
[]
[[1]
 [3]
 [4]
 [5]]
[]
[[1]]
[]
[[1]]
[[1]]
[]
[]
[[1]
 [2]
 [3]]
[[1]]
[[4]]
[[1]
 [2]]
[[1]]
[[1]
 [4]
 [5]
 [7]]
[[1]]
[[1]]
[[1]]
[[1]
 [2]
 [3]
 [4]]
[[1]]
[]
[]
[[1]
 [2]]
[[1]]
[[1]
 [2]]
[[1]
 [2]]
[]
[[1]]
[]
[[1]]
[[1]
 [2]]
[[5]
 [6]]
[]
[[1]
 [2]
 [3]
 [6]]
[[1]
 [2]]
[[1]]
[[1]
 [2]]
[[25]
 [26]
 [34]
 [35]
 [41]
 [42]
 [44]
 [45]
 [46]
 [47]
 [48]]
[]
[[2]]
[[1]]
[]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[]
[[1]
 [2]]
[[1]]
[]
[[1]
 [2]
 [3]
 [4]
 [5]]
[[1]
 [2]]
[[1]
 [3]]
[[2]]
[[2]
 [3]
 [4]
 [5]
 [6]]
[[1]
 [2]]
[[1]]
[[2]]
[[1]
 [2]]
[[1]]
[[1]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1]
 [2]
 [3]]
[[1]]
[]
[]
[[1]
 [2]]
[[1]]
[]
[]
[[1]]
[[1]
 [2]
 [3]]
[[1]
 [2]]
[[1]
 [2]]
[[1]]
[[1]
 [2]
 [3]]
[]
[[1]
 [2]]
[]
[[ 1]
 [ 2]
 [ 3

 [2]]
[]
[[1]
 [2]
 [3]
 [4]]
[[1]
 [2]
 [3]
 [4]
 [5]]
[[1]
 [2]]
[[1]]
[[1]]
[[1]]
[[1]
 [2]
 [3]
 [4]]
[[1]
 [2]]
[[1]]
[[1]
 [2]
 [3]
 [4]]
[[1]
 [2]]
[[2]
 [3]]
[[1]
 [4]]
[[1]]
[[1]
 [2]
 [3]]
[]
[[1]]
[[1]]
[[3]]
[[1]]
[[7]]
[[1]
 [2]
 [3]
 [4]]
[[1]
 [2]
 [3]
 [4]]
[]
[[1]
 [2]]
[[1]
 [2]]
[[1]]
[]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1]
 [2]]
[[1]]
[[1]]
[]
[[1]
 [2]]
[[1]]
[[1]]
[]
[[ 6]
 [ 7]
 [ 8]
 [12]
 [14]]
[[1]]
[[1]
 [2]
 [3]
 [4]
 [5]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
[[1]
 [2]
 [3]
 [4]
 [5]]
[[1]]
[[27]]
[[1]]
[[1]]
[]
[[1]]
[[1]
 [2]]
[]
[[1]]
[[1]]
[[1]]
[[1]
 [2]]
[[1]
 [2]
 [3]
 [4]]
[[1]]
[[1]
 [2]
 [3]]
[]
[[1]]
[[1]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [22]
 [23]]
[]
[[1]]
[[1]]
[[1]]
[[ 9]
 [10]
 [11]
 [13]]
[[1]
 [2]
 [3]
 [4]]
[[1]
 [2]
 [3]
 [4]]
[[1]]
[]
[[1]]
[[1]]
[[1]
 [2]
 [3]]
[[ 5]
 [ 6]
 [ 9]
 [10]
 [14]
 [15]
 [17]]
[[1]]
[[1]]
[[8]]